version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: server
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb3?schema=public
      - SECRET=asguyfsRYTGUIB23456789
      - END=30d
      - NODE_ENV=development
      - PORT=8000
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./server:/server

  pubsub:
    build: ./pubsub
    container_name: pubsub
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./pubsub:/pubsub

  worker:
    build: ./worker
    container_name: worker
    ports:
      - "8001:8001"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./worker:/worker

volumes:
  db:
